on:
  push:
    branches:
      - main
      - 'release**'
  pull_request:
    branches:
      - main
      - 'release**'
jobs:
    unittest:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v2

        - name: Configure git for private modules
          run: git config --global url."https://x-access-token:${{ secrets.PRV_GITHUB_TOKEN }}@github.com/openinfradev".insteadOf "https://github.com/openinfradev"

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17

        - name: Build
          run: go build -v ./...

        - name: Test
          run: go test -v -cover ./...